# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_uuid', models.UUIDField(editable=False)),
                ('urn', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('groups', models.CharField(max_length=100)),
                ('siteid', models.IntegerField()),
                ('first_seen', models.DateTimeField(verbose_name='first seen')),
                ('last_seen', models.DateTimeField(verbose_name='last seen')),
                ('weeknum', models.IntegerField()),
                ('rutf_in', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rutf_out_carton', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rutf_bal_cartons', models.DecimalField(decimal_places=2, max_digits=8)),
                ('f75_bal_carton', models.DecimalField(decimal_places=2, max_digits=7)),
                ('f100_bal_carton', models.DecimalField(decimal_places=2, max_digits=7)),
                ('confirm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_uuid', models.UUIDField(editable=False)),
                ('urn', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('groups', models.CharField(max_length=100)),
                ('siteid', models.IntegerField()),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('weeknum', models.IntegerField()),
                ('role', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('age_group', models.CharField(max_length=20)),
                ('beg', models.IntegerField()),
                ('amar', models.IntegerField()),
                ('tin', models.IntegerField()),
                ('tout', models.IntegerField()),
                ('dcur', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('defu', models.IntegerField()),
                ('dmed', models.IntegerField()),
                ('confirm', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_uuid', models.UUIDField(editable=False)),
                ('urn', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('groups', models.CharField(max_length=100)),
                ('siteid', models.IntegerField()),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('level', models.CharField(max_length=20)),
                ('weeknum', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('rutf_in', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rutf_used_carton', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rutf_used_sachet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rutf_bal_cartons', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rutf_bal_sachet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('f75_bal_carton', models.DecimalField(decimal_places=2, max_digits=7)),
                ('f75_bal_sachet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('f100_bal_carton', models.DecimalField(decimal_places=2, max_digits=7)),
                ('f100_bal_sachet', models.DecimalField(decimal_places=2, max_digits=7)),
                ('confirm', models.CharField(max_length=20)),
            ],
        ),
    ]
