# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-29 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('contact_uuid', models.UUIDField(editable=False)),
                ('urn', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('groups', models.CharField(max_length=100)),
                ('siteid', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('post', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'registration',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='lga',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'managed': False},
        ),
    ]
