# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170129_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siteid',
            fields=[
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('siteid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('state', models.TextField(blank=True, null=True)),
                ('state_num', models.TextField(blank=True, null=True)),
                ('lga', models.TextField(blank=True, null=True)),
                ('lga_num', models.TextField(blank=True, null=True)),
                ('ward', models.TextField(blank=True, null=True)),
                ('sitename', models.TextField(blank=True, null=True)),
                ('x_lat', models.FloatField(blank=True, null=True)),
                ('y_lat', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'siteid',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='lga',
            table='lga',
        ),
        migrations.AlterModelTable(
            name='program',
            table='program',
        ),
    ]
