# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170210_1532'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='siteid',
            table='siteids',
        ),
    ]
