# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170214_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_admin',
            fields=[
                ('index', models.IntegerField()),
                ('state', models.TextField(blank=True, null=True)),
                ('state_num', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'first_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Second_admin',
            fields=[
                ('index', models.BigIntegerField()),
                ('lga', models.TextField(blank=True, null=True)),
                ('lga_num', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'second_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('index', models.IntegerField()),
                ('siteid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sitename', models.TextField(blank=True, null=True)),
                ('ward', models.TextField(blank=True, null=True)),
                ('x_long', models.IntegerField(blank=True, null=True)),
                ('y_lat', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'site',
                'managed': False,
            },
        ),
    ]
