# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_first_admin_second_admin_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={},
        ),
    ]
