# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170428_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='lga_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='state_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='contact_uuid',
            field=models.CharField(editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='urn',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
