# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170428_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdatedAPICall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
