# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_lastupdatedapicall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastupdatedapicall',
            name='kind',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
